#@TYPE: Machine
#@NAME: bananapi-bpi-f3
#@SOC: SpacemiT K1
#@DESCRIPTION: Machine configuration for the Banana Pi BPI-F3 board

require conf/machine/u-boot-utilities.inc
require include/spacemit-k1-common.inc

# Use an initramfs and populate it with the kernel modules and key firmware
INITRAMFS_IMAGE ?= "core-image-initramfs-boot" 
INITRAMFS_MAXSIZE ?= "262144"
PACKAGE_INSTALL:append:pn-core-image-initramfs-boot = " ${MACHINE_EXTRA_RRECOMMENDS}"

IMAGE_BOOT_FILES ??= " \
    ${KERNEL_IMAGETYPE} \
    ${INITRAMFS_IMAGE_NAME}.${INITRAMFS_FSTYPES} \
    ${@make_dtb_boot_files(d)} \
"

#============================================
# Kernel Configuration
KERNEL_CLASSES = "kernel"
KERNEL_DTB_PREFIX = "spacemit/"
KERNEL_DEVICETREE = " \
    ${KERNEL_DTB_PREFIX}k1-x_deb1.dtb \
"
KERNEL_IMAGETYPE = "Image.gz"
#============================================

#============================================
# Uboot Configuration
UBOOT_MACHINE = "k1_defconfig"
UBOOT_DTB_BINARY = "k1-x_spl.dtb"
#============================================

WIC_COMPRESSION_EXTENSION = ".xz"
IMAGE_FSTYPES = "wic${WIC_COMPRESSION_EXTENSION} wic.bmap ext4"

# Do not update fstab file when using wic images
WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"

WKS_FILE ?= "bananapi-bpi-f3.wks"
